version: '3.1'

volumes:
  bundle:

services:

  app:
    image: ruby:2.5.1
    working_dir: /app
    command: ruby app.rb
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    logging:
      options:
        max-size: "200k"
        max-file: "10"
